### ISSUE TITLE
Elixir Formatter Error

### ISSUE THREAD

**Issue by jamesaspinwall** [rgreenjr/atom-elixir-formatter#12]
Just installed version 0.4.0.

I have set my local elixir path to point to my local elixir path:
```
/Users/jaspinwall/git/elixir/bin/elixir
```

My global elixir is:
```
~/git/elixir[master]$ elixir --version
Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
```
When I ALT-CTL-F, I get:
```
Elixir Formatter Error
mix format failed for file: stdin
** (SyntaxError) stdin:6: unexpected token: end
    (elixir) lib/code.ex:443: Code.format_string!/2
    (mix) lib/mix/tasks/format.ex:163: Mix.Tasks.Format.format_file/3
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3```

**Comment by rgreenjr** [comment]
Hi @jamesaspinwall – Thanks for the bug report. The `unexpected token: end` error usually happens for one of two reasons:

First, if no code is selected and <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>F</kbd> is invoked, the formatter attempts to format the entire. This error would mean there is an extra `end` statement somewhere in the file. 

Second, if code *is* selected and <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>F</kbd> is invoked, the formatter attempts to format just the selected code. This error would mean the selected code contains an extra `end` statement.

Can you try formatting the file again (without any code selected) and see if that works?

**Comment by rgreenjr** [comment]
@jamesaspinwall – Have you had a chance to try formatting the file again given the above details?

**Comment by rgreenjr** [comment]
@jamesaspinwall – I'm closing this issue for now. Hopefully the details above were helpful. Please feel free re-open if that's not the case.
