### ISSUE TITLE
Is it possible remove previous notifications?

### ISSUE THREAD

**Issue by thiagogsr** [rgreenjr/atom-elixir-formatter#13]
Hi,

Your plugin is awesome, congrats. I would like to suggest a feature: close previous notifications when you can format as well. Example: I save the file but it has a syntax error and I receive a notification then I fix the syntax error and the formatter runs as well, but the notification stills opened.

Is there a way to close automatically when you call `insertText` [here](https://github.com/rgreenjr/atom-elixir-formatter/blob/master/lib/formatter.js#L31)? I don't know the `atom` documentation to answer it.

Thank you

**Comment by rgreenjr** [comment]
Hi @thiagogsr – that is a great idea. It should be easy to implement, so I'll try to get it done today.

Thanks! 👍

**Comment by thiagogsr** [comment]
It is working perfectly, thanks for the fast answer.
