### ISSUE TITLE
Bookmarks are removed after formatting

### ISSUE THREAD

**Issue by balduncle** [rgreenjr/atom-elixir-formatter#14]
Every time I format or save a file I lose all of my bookmarks.  I haven't researched further but am hoping it is possible to have Atom attempt to save the bookmarks despite reformatting.

Thanks for the plugin.  :)

**Comment by rgreenjr** [comment]
Hi @balduncle – I've haven't used bookmarks before and didn't notice they were being deleted. Thanks for the heads-up.

I did a little research and this looks like it will be difficult to accomplish. The Elixir code formatter outputs raw text, so there's no direct way to associate a bookmark's location before/after formatting. Let me know if you think of something during your research. I'd be happy to try and get this working.

**Comment by balduncle** [comment]
I just confirmed that a similar package (https://atom.io/packages/go-imports) is able to preserve bookmarks to some extent even though the file gets reorganized on save.

The relevant code seems to be at https://github.com/abiosoft/atom-go-imports/blob/master/lib/go-imports.coffee.  Note that `goimports -w filename` modifies the file in place.

I'll keep researching.

**Comment by balduncle** [comment]
Maybe this will work by simply changing the formatting to run .afterSave instead of .onWillSave, and then just call .save again after formatting is complete.

In go the go-imports command is invoked on save via the go-plus plugin, at https://github.com/joefitzgerald/go-plus/blob/master/lib/format/formatter.js, unless you configure a different go formatter to run on save.

**Comment by rgreenjr** [comment]
Excellent! I installed `go-plus` and it does (mostly) maintain bookmarks after formatting. The only caveat is that lines changed during formatting lose their bookmarks. But once a file has been saved/formatted, its bookmarks should largely stay in tact through subsequent saves/formats. 

I'm pretty sure I can make the necessary modifications and push a release out later today. 👍

**Comment by rgreenjr** [comment]
@balduncle – The necessary changes were very minor. I just published v0.4.3. Please take a look and let me know if it works for you. Thanks.

**Comment by balduncle** [comment]
Works great!  Thanks for the incredible turnaround.  Much appreciated.

**Comment by rgreenjr** [comment]
Fantastic. Thanks again for the bug report. 🎉
