### ISSUE TITLE
Formatter still runs even when package is disabled

### ISSUE THREAD

**Issue by randycoulman** [rgreenjr/atom-elixir-formatter#16]
Atom version: 1.23.3
atom-elixir-formatter version: 1.0.0

To reproduce:
- Set Format on Save option to `Only if project includes a .formatter.exs file`
- Open a project that has a `.formatter.exs` file
- Open a file from outside the project.  Choosing `Atom | Config...` from Atom's menu is a good option
- Disable the atom-elixir-formatter plugin
- Make a simple change and attempt to save
- Notice that the same error as #15 is shown in the console

My limited testing shows that this only happens if the file was opened before disabling the plugin.  If the file is opened afterwards, the formatter is not run.

**Comment by rgreenjr** [comment]
Same for this one – I'll look into it as soon as I get back in town. Thanks for the bug report.

**Comment by rgreenjr** [comment]
Hi @randycoulman – I just published version 1.0.2 with a fix for this bug. I was surprised to find that packages have to manually check if they've been disabled if they were enabled at launch. Please take a look and let me know if it works for you. Thanks again.

**Comment by randycoulman** [comment]
1.0.2 seems to fix the problem.  Thanks!  Seems like Atom shouldn't be sending events to disabled plugins, so maybe this is really an upstream problem?
