### ISSUE TITLE
Feature request: would like to add "--check-equivalent" to "mix format" command

### ISSUE THREAD

**Issue by ideaMarcos** [rgreenjr/atom-elixir-formatter#18]
```
--check-equivalent - check if the files after formatting have the same AST as before formatting. If the ASTs are not equivalent, it is a bug in the code formatter. This option is recommended if you are automatically formatting files.
```

I'm not sure if it would be best to hard code this in lib/formatter.js or making it optional.

**Comment by rgreenjr** [comment]
Hi @ideaMarcos – I like this idea. I'd considered adding `--check-equivalent` earlier, but thought it might be too slow. However, I did some timing tests last night and there's no perceptible delay. I'll add this feature and push a new release shortly.

**Comment by rgreenjr** [comment]
Hi @ideaMarcos – I just pushed version 1.0.3 with `--check-equivalent`. Thanks again for the feature request.
