### ISSUE TITLE
Formatter ignoring options in subdirectory .formatter.exs

### ISSUE THREAD

**Issue by robmckinnon** [rgreenjr/atom-elixir-formatter#19]
Formatter is ignoring options set in a subdirectory's `.formatter.exs`.

For example, given an umbrella phoenix project structure:

```
my_app/.formatter.exs
my_app/apps/my_app_web/.formatter.exs
```

And given `subdirectories` [option](https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-formatting-options) is set in `my_app/.formatter.exs`, like so:
```elixir
[
  inputs: ["{mix,.formatter}.exs", "config/*.exs"],
  subdirectories: ["apps/*"]
]
```
And `locals_without_parens` option is set in `my_app/apps/my_app_web/.formatter.exs`, like so:
```elixir
[
  locals_without_parens: [plug: 1],
  export: [locals_without_parens: [plug: 1]],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
```

When Atom opens a project from the root directory, i.e. `atom my_app`, when formatter is run on file in `my_app/apps/my_app_web` it takes configuration from `my_app/.formatter.exs`. Expected behaviour is that it would take configuration from `my_app/apps/my_app_web/.formatter.exs`

So parens are added to `plug :fetch_session` in `my_app/apps/my_app_web/lib/router.ex`. It becomes `plug(:fetch_session)`.

Expected behaviour is for formatter to honour `my_app/apps/my_app_web/.formatter.exs` configuration and not add parens to `plug :fetch_session`.

**Comment by rgreenjr** [comment]
Thanks for the bug report. I'll carve out some time this weekend to investigate.

**Comment by robmckinnon** [comment]
@rgreenjr Were you able to replicate this issue?

**Comment by rgreenjr** [comment]
Hi @robmckinnon – I was able to reproduce the bug this weekend using your example (thanks).

I somehow missed this [commit](https://github.com/elixir-lang/elixir/commit/cb9bf1b497b541c7f8a76e27e13b68281e356295#diff-35de394ee1320104651f86d1fc16db4d) on February 28, 2018 where the `:subdirectories` keyword was added. I wasn't aware of the new behavior until now. There are a few possible ways to support this new behavior, but each has its pros and cons.

Atom Elixir Formatter currently interacts with the Elixir formatter via stdin/stdout. The Elixir formatter doesn't know which file it's formatting, but has access to the root `.formatter.exs` via the current working directory. This design allows users to format entire files, or just currently selected text, or even unsaved buffers (which aren't on the file system yet). The new `:subdirectories` behavior complicates things. The Elixir formatter needs to know which `.formatter.exs` to use when formatting text.

The easiest solution would be to remove support for formatting text selections and unsaved buffers (which I imagine aren't frequently used). Then the Elixir formatter could be given the full path of the file being formatted.

Alternatively, I could parse the root `.formatter.exs` and pass the appropriate subdirectory `.formatter.exs` to the Elixir formatter using the `--dot-formatter` argument. This would maintain all existing functionality, but add a bit of overhead to each save.

I'm not sure which direct to go at this time and want to think about it more. Any feedback you have would be welcome.

**Comment by AndrewDryga** [comment]
This happens to me to, can't really use this plugin because it keeps ignoring `locals_without_parens` defined for a web app within an umbrella.

**Comment by novaugust** [comment]
Similarly, I have a project I work in where the elixir project is just subdirectory, so the `.formatter.exs` file isn't in the root but is instead at `/elixir-project/.formatter.exs`. It doesn't get picked up/used, and adding a `.formatter.exs` to the root directory won't work since that's not a mix project

**Comment by rgreenjr** [comment]
Thanks for the feedback @AndrewDryga and @novaugust.

I think the best path forward is to remove support for formatting text selections and unsaved buffers. That functionality probably isn't used very often anyway. Then the Elixir formatter can be given the full path of the file being formatted, allowing the use of `.formatter.exs` files in subdirectories.

I'm too busy at work to make these changes right now, but I'll hopefully be able to carve out time in the next two to three weeks.

**Comment by novaugust** [comment]
> I think the best path forward is to remove support for formatting text selections and unsaved buffers. That functionality probably isn't used very often anyway.

Yeah, I've never touched either. format-on-save + the occasional manually triggered format-file are all I'm ever after =)

>I'm too busy at work to make these changes right now, but I'll hopefully be able to carve out time in the next two to three weeks.

Pffft, take two to three years if you want. I don't think we ever made any sort of support agreement ;)

**Comment by rgreenjr** [comment]
@novaugust – I think I was able to fix this in version 1.0.4. Will you please upgrade and see if `.formatter.exs` files in subdirectories are correctly being used?

**Comment by novaugust** [comment]
@rgreenjr it works great! thanks so much, quite appreciated. 

only thing to note is the setting for when to format has "Only if project has a formatter.exs file" as an option either needs to look around for the file or just include the word `root` like "If project has .formatter.ex in the root" ;) 

Cheers!

**Comment by rgreenjr** [comment]
@novaugust Great catch on settings – that didn't even cross my mind. Thanks!
