### ISSUE TITLE
Getting empty errors and no reformatting

### ISSUE THREAD

**Issue by bryanstearns** [rgreenjr/atom-elixir-formatter#2]
@rgreenjr I'm excited to be able to use the new formatting features from Atom, so thanks for putting this together!

Unfortunately, it's not working: the first time I tried to format, I got a red error box with a bunch of warnings from my current project's development dependencies (stuff having to do with missing parens on local function calls, meh). After that first time, I still get the red error box, but with nothing in it (!) --

<img width="469" alt="clown_car_test_exs_ ___code_clown_car" src="https://user-images.githubusercontent.com/5131/31460876-8f14a67e-ae7c-11e7-9a87-ccd68075d799.png">

Turning off the setting to see errors means I don't get the box, but I still get no reformatting.

I use [asdf](https://github.com/asdf-vm/asdf) to manage my Elixir versions, and I've configured the package to point at the "master" installation's `mix` executable. I've tried out `mix format --print <path>` from the command line with this installation, using a full path to format a file in my current project, and it worked.

My current project has a .tool-versions file (asdf's configuration) to select Elixir 1.5; is that a deal-breaker? (that is, does the formatter only work against projects using the same Elixir version?) I was hoping they'd be independent, but the first error I got (with the dependency compile warnings) makes me think that the formatter has to compile everything before it reformats.

When I tried out `mix format --print <path>` from the command line, I did it from a directory that contained only the `.tool-versions` file that selected the master elixir installation. Since that worked, it makes me think that there's a way to set up the context that your package is using to run `mix` that'd be more independent of the target project's selected Elixir version.

(I'm using Atom 1.21.0 on macOS 10.13; I'm not familiar with how Atom packages are debugged so I don't know if there's a useful Atom log produced by the formatting operation that I could attach here. Let me know if there is, or if you have other questions or suggestions!)

Again, thanks for building this tool - it's going to be a great help for me, since I'm OCD about formatting and spend a lot of typing time getting it right! :-)

**Comment by rgreenjr** [comment]
Hi @bryanstearns, thanks for the detailed bug report. 

I think I have a solution. The issue is that users need a way to specify both the ```mix``` executable and the ```elixir``` executable when running the formatter.

I just pushed a new release (version 0.1.4). It adds an **Elixir Executable** setting.  Please update your ```atom-elixir-formatter``` and set **Elixir Executable** and **Mix Executable** to point to your locally installed version of the Elixir master branch. For example, I have mine set to ```/Users/rgreen/code/elixir/bin/elixir``` and ```/Users/rgreen/code/elixir/bin/mix```.

I've tested this with a project that's using ```asdf``` and ```.tool-versions``` set to use Elixir 1.5.1.

Please let me know if you have any trouble and if this fixes the problem. Thanks.

**Comment by bryanstearns** [comment]
@rgreenjr Awesome -- it's working great, and no error messages (even after cleaning out all the compiled stuff from my project). Thanks again (and thanks for the quick response!).

**Comment by rgreenjr** [comment]
Fantastic, thanks @bryanstearns. 👍
