### ISSUE TITLE
Formatter error message

### ISSUE THREAD

**Issue by karmajunkie** [rgreenjr/atom-elixir-formatter#20]
I'm a relatively new atom user trying to configure my editor for Elixir development, and I'm running into this error message when I try to save with the formatter plugin:

### Elixir Formatter Error
```
bash: ga: line 1: syntax error: unexpected end of file
bash: error importing function definition for `ga'
bash: za: line 1: syntax error: unexpected end of file
bash: error importing function definition for `za'
```

I'm using `asdf` to manage elixir versions, and I've gotten the same message whether I use the default value for `atom-elixir-formatter.elixirExecutable` or point it at the shim that asdf creates.

I don't know where to begin debugging this issue, could use any tips you can offer.

I'm on Atom 1.25.0, and I'm using Proton for my configuration. I've tried starting Atom from the Finder, from the console (in the cwd of my project), as well as unrelated directories, without much success.

**Comment by rgreenjr** [comment]
Hi @karmajunkie – I use `asdf` quite a bit myself with Atom, but I've never seen that error message. Do you get this error when editing any Elixir file, or one in particular?

**Comment by karmajunkie** [comment]
Well, this is kind of bizarre...

I went to verify that it was happening on other files as well as the one I've been testing with (spoiler alert: its not.)

1) I closed down the window of the project I'd been working on today (a ruby project)
2) opened a new window
3) reloaded the elixir project I was testing with yesterday

First weird thing is that atom wasn't repainting the editor of the file fully when I'd make a minor change like inserting a newline.

so I opened a different elixir file, and the reformatting seems to be working in that buffer. So I switched back to the original file, still having painting issues. I closed that buffer, then reopened the file in question in a new one. Now the reformatting is working there.

Now, I close down atom and reopen it using the terminal commands.  So now I'm seeing the error again.

I'm thinking this may be related to me using proton, which is written in clojurescript. The error message looks suspiciously like minified javascript.  I'm going to uninstall that and try it fresh and report back.

**Comment by karmajunkie** [comment]
Yeah, this looks like its related to the use of proton-mode. I'm going to go ahead and close this, thanks for taking a look at it!

**Comment by rgreenjr** [comment]
Hey @karmajunkie – Glad to hear you figured it out. By the way, I see that we both live in Austin. Hope to see you around sometime.

**Comment by karmajunkie** [comment]
Oh cool, I didn't see that! I make it out to meetups every once in awhile, I hope we do catch up!  I'll drop you a line via email...
