### ISSUE TITLE
Running in subdirectory with `.formatter.exs` file breaks

### ISSUE THREAD

**Issue by dnsbty** [rgreenjr/atom-elixir-formatter#26]
Hi Ron! Thanks so much for creating this plugin. It has been super helpful to me.

I'm currently running version 1.0.6 on macOS Mojave (10.14), using Elixir 1.8.0 and Erlang 21.2.2.

When I format `/priv/repo/migrations/some_file.ex`, I get the following message:
![image](https://user-images.githubusercontent.com/3421625/51859855-60549a80-22f5-11e9-8985-02685f447aac.png)
For search purposes:
```
Elixir Formatter Error
** (Mix) Unknown dependency :ecto_sql given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :dev
```

My `.formatter.exs` file in the same directory contains:
```elixir
[
  import_deps: [:ecto_sql],
  inputs: ["*.exs"]
]
```

I also have a `.formatter.exs` in my root directory that looks like:
```elixir
[
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

And my `mix.exs` file in the root directory looks like:
```
defmodule MyProject.MixProject do
  use Mix.Project

  def project do
    [
      ...
      deps: deps(),
      ...
    ]
  end

  defp deps do
    [
      ...
      {:ecto_sql, "~> 3.0"},
      ...
    ]
  end
  ...
end
```

In the [docs for the `format` mix task](https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-formatting-options), it looks like the formatter needs to be run on the level of the `mix.exs` file in order for the `import_deps` to work, since the root `.formatter.exs` will contain a list of `subdirectories` that have custom `.formatter.exs` files that should be used.

I can maybe look into creating a PR a little later, but my thinking would be to look for the closest directory up with a `mix.exs` file and then `cd` into that and run `mix format` there, but I'm not sure if that will break others' setups.

**Comment by rgreenjr** [comment]
Hi @dnsbty – Thanks for the detailed bug report. I'll carve out time this weekend to investigate and get back to you.

**Comment by tpitale** [comment]
@rgreenjr I'm encountering this problem now as well. We have an umbrella app project and I'm guessing that makes things more complex.

**Comment by rgreenjr** [comment]
@tpitale Thank you for the additional info. 

Work commitments are preventing me from fixing this right now. However, I hope to have time in the coming months to investigate and address the issue. 🤞

**Comment by tpitale** [comment]
If you have any ideas as to where or why this is happening I am happy to dig in and try to fix it.

**Comment by JohnSmall** [comment]
I've got the same problem as well. I found that running mix format on the command line like this

     mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs} " "priv/**/*.{ex,exs}"

Doesn't generate the error, though I can artificially introduce an error into the migrations and that will be picked up, so the migrations are definitely being scanned. 

Does this package run `mix format etc` on the file after it's been saved or use some magic to get `mix format` to check the Atom edit buffer? 

It's very strange that running `mix format` from the command line passes the migrations as OK, but this package passes some parameters to `mix format` that makes it generate an error.

**Comment by JohnSmall** [comment]
Ah, I see the problem. If I go into the `/migrations` directory, which contains a `.formatter.exs` file then when I run 

    mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs} " "priv/**/*.{ex,exs}"

I get the exact same error that Atom displays. So the workaround is simply to delete `.formatter.exs` from the migrations directory. 

It is only workaround though.

**Comment by rgreenjr** [comment]
@JohnSmall Thanks for the additional feedback.

**Comment by rgreenjr** [comment]
@tpitale I appreciate the offer to help. The results from @JohnSmall have me guessing that the formatter is expecting to be run at the project root level and that invoking it directly in subdirectories is causing problems.

**Comment by rgreenjr** [comment]
I spent some time last night digging into this. I believe I can resolve this issue and maintain all existing functionality by changing the way `mix format` is invoked. Specifically, two changes need to be made:

1. Set `cwd` to project root instead of the directory containing the nearest `.formatter.exs` file.
2. Pass the nearest `.formatter.exs` file to `mix format` via `--dot-formatter`.

I'm going to do some additional testing and will hopefully be able to push a release later this week.

**Comment by rgreenjr** [comment]
Hey everyone – I just published v2.0.0, which I believe will fix this issue. It required significant changes, so please take a look and let me know if it works for each of you.

**Comment by tpitale** [comment]
Finally updated, working great for me!

**Comment by rgreenjr** [comment]
It's been over three weeks now, so I'm going to close this issue resolved.
