### ISSUE TITLE
Elixir Formatter Error

### ISSUE THREAD

**Issue by KamilLelonek** [rgreenjr/atom-elixir-formatter#31]
```
warning: --check-equivalent has been deprecated and has no effect
  (mix 1.13.0) lib/mix/tasks/format.ex:191: Mix.Tasks.Format.run/1
  (mix 1.13.0) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
  (mix 1.13.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
  (elixir 1.13.0) src/elixir_compiler.erl:73: :elixir_compiler.dispatch/4
  (elixir 1.13.0) src/elixir_compiler.erl:58: :elixir_compiler.compile/3
  (elixir 1.13.0) src/elixir_lexical.erl:15: :elixir_lexical.run/3
```

After upgrading to Elixir `1.13.0`.

![image](https://user-images.githubusercontent.com/3199333/145209212-13de0b6d-0f7c-48f3-82dc-384c00a7ae44.png)

Will probably require changing the following line: https://github.com/rgreenjr/atom-elixir-formatter/blob/master/lib/formatter.js#L56

**Comment by sn3p** [comment]
Same issue here.

**Comment by rgreenjr** [comment]
Thanks for for notice @KamilLelonek and @sn3p. This should be simple to resolve. I will work this weekend to resolve the issue and push a fix.

**Comment by rgreenjr** [comment]
@KamilLelonek @sn3p I just pushed v2.0.1 with a fix for this issue. Please update when you get a chance and let me know if you run into anymore issues. Thanks!

**Comment by KamilLelonek** [comment]
Works for me without warnings! Thanks :)

**Comment by sn3p** [comment]
Works like a charm, many thanks!
