### ISSUE TITLE
Format on save working unexpectedly when text selected

### ISSUE THREAD

**Issue by lukaszsamson** [rgreenjr/atom-elixir-formatter#4]
Expected:
Format on save formats the whole file
Current:
only selection is formatted

This results in either Formatter error or breaking the syntax in saved file

**Comment by rgreenjr** [comment]
Thanks @lukaszsamson. Very good catch. I'll release a bug fix for this today.

**Comment by rgreenjr** [comment]
@lukaszsamson I just released version 0.1.6 with a fix for this issue. It should now format the entire file on save even if a text selection exists.

Please take a look and let me know if you have any problems. Thanks!

**Comment by lukaszsamson** [comment]
I can confirm it now works as expected.
