### ISSUE TITLE
I cannot see a settings tab

### ISSUE THREAD

**Issue by CrowdHailer** [rgreenjr/atom-elixir-formatter#6]
In atom I see no settings button associated with the `atom-elixir-formatter` project.

I therefore do not know how to do the following
> set Elixir Executable and Mix Executable to the absolute paths of the elixir and mix executables.

**Comment by rgreenjr** [comment]
The package settings in Atom can be a little hard to find. 

To open Settings you can:

- Use the _Atom > Preferences_ menu item in the menu bar
- Use the <kbd>Cmd</kbd> + <kbd>,</kbd> keybinding

Then use the search field to find `atom-elixir-formatter` and then click on its _Settings_ button.

<img width="752" alt="screen shot 2017-10-13 at 8 50 20 am" src="https://user-images.githubusercontent.com/37242/31549397-a622de62-aff3-11e7-98a3-525ee8a6160e.png">

I hope this helps. 🍀

**Comment by CrowdHailer** [comment]
Thanks, yes it is a little hard to find.

That is exactly what I found and I see everything you posted above minus the button with a cog and the word settings in it. Slightly odd.

**Comment by rgreenjr** [comment]
Maybe try restarting Atom. I've seen that fix all kinds of issues.

**Comment by CrowdHailer** [comment]
Turn it off and on again. 

The classics. thanks
