### ISSUE TITLE
Formatter doesn't format and instead just inserts newline

### ISSUE THREAD

**Issue by whatyouhide** [rgreenjr/atom-elixir-formatter#8]
Hey there,

thanks for this package! I've been using it successfully since it was released but now I'm having trouble with it. Basically, whenever I format through "Atom Elixir Formatter: Format", it only inserts a newline and doesn't perform any actual formatting. I tried this with a coworker's fresh install and it behaved the same. Am I missing something obvious? 🤔 

Thanks for the help anyways :D

**Comment by rgreenjr** [comment]
Thanks for the bug report. I wonder if this has something to do with Atom Elixir Formatter switching in version 0.2.1 to using `stdin` and `stdout` to communicate with the Elixir code formatter.

Can you tell me what version of Atom, Atom Elixir Formatter, and OS you're using?

Also, does it fail only when you format through "Atom Elixir Formatter: Format", or does it also format incorrectly when you enable **Format on Save** and save changes?

Lastly, can you tell me when this first started happening?

Thanks.

**Comment by whatyouhide** [comment]
Hey @rgreenjr, it only happens when I run the command. It doesn't happen when **Format on Save** is active. I'm using

* macOS 10.12.6
* Atom Elixir Formatter 0.2.3
* Atom 1.21.2

**Comment by rgreenjr** [comment]
I think I've fixed the problem. Empty buffer selections weren't being handled correctly. 

I just published v0.2.2, which should correct the issue. Please update and let me know if it works for you.

Thanks!

**Comment by whatyouhide** [comment]
@rgreenjr it looks like it works now, thanks! 💟

**Comment by rgreenjr** [comment]
Fantastic. 👍
